/**
 * Generate the README "Implementation status" block from real repo state
 * (DOCS-001). Never hand-edit counts again: this script is the only writer.
 *
 * Sources of truth:
 *  - commit:            git rev-parse HEAD
 *  - migration count:   db/migrations/*.sql
 *  - benchmark corpus:  BENCHMARK_SUITE_VERSION + REVIEWED_BENCHMARK_CASES
 *                       imported from apps/api/src/eval/benchmarkCorpus.ts
 *
 * Usage:
 *   bun scripts/project_status.ts          # print the markdown block
 *   bun scripts/project_status.ts --write  # splice it into README.md
 *                                             (between the project-status
 *                                              markers)
 */
import { execSync } from 'node:child_process'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import {
	BENCHMARK_SUITE_VERSION,
	REVIEWED_BENCHMARK_CASES,
} from '../apps/api/src/eval/benchmarkCorpus'

const BEGIN =
	'<!-- project-status:begin (generated by scripts/project_status.ts — do not edit inside) -->'
const END = '<!-- project-status:end -->'

function git(args: string): string {
	try {
		return execSync(`git ${args}`, { encoding: 'utf8' }).trim()
	} catch {
		return ''
	}
}

const commit = git('rev-parse --short HEAD') || 'unknown'
const migrationFiles = readdirSync('db/migrations').filter((f) =>
	f.endsWith('.sql'),
)
const migrationCount = migrationFiles.length

const families: Record<string, number> = {}
let tuning = 0
let heldOut = 0
for (const c of REVIEWED_BENCHMARK_CASES) {
	families[c.family] = (families[c.family] ?? 0) + 1
	if (c.split === 'tuning') tuning++
	else heldOut++
}
const caseCount = REVIEWED_BENCHMARK_CASES.length
const familyList = Object.entries(families)
	.map(([name, n]) => `${name} ${n}`)
	.join(', ')

const generatedAt = new Date().toISOString().slice(0, 10)

const block = `${BEGIN}
Evidence is generated, not hand-written: \`bun scripts/project_status.ts --write\` (last generated ${generatedAt} at commit \`${commit}\`).
Counts below are read from the repository at generation time; CI and issue badges stay live.

- Migrations applied in order: \`db/migrations\` — **${migrationCount}** files
- Reviewed benchmark corpus: \`${BENCHMARK_SUITE_VERSION}\` — **${caseCount} cases** (${familyList}; ${tuning} tuning / ${heldOut} held-out)
- CI: [![CI](https://github.com/ther12k/aifiqh/actions/workflows/ci.yml/badge.svg)](https://github.com/ther12k/aifiqh/actions/workflows/ci.yml)
- Open issues: [![issues](https://img.shields.io/github/issues-raw/ther12k/aifiqh)](https://github.com/ther12k/aifiqh/issues)
${END}`

if (process.argv.includes('--write')) {
	const readme = readFileSync('README.md', 'utf8')
	const beginIdx = readme.indexOf(BEGIN)
	const endIdx = readme.indexOf(END)
	if (beginIdx < 0 || endIdx < beginIdx) {
		console.error(
			'✗ README.md lacks the project-status markers — add them once, then re-run',
		)
		process.exit(1)
	}
	const updated =
		readme.slice(0, beginIdx) + block + readme.slice(endIdx + END.length)
	writeFileSync('README.md', updated)
	console.log(
		`✓ README.md status block updated (commit ${commit}, ${migrationCount} migrations, ${caseCount} benchmark cases)`,
	)
} else {
	console.log(block)
}
